### ISSUE TITLE
SCM_model

### ISSUE THREAD

**Issue by forlornLT** [akjayant/Autonomous-Driving-via-RL#4]
Hello, when I ran the ver3.0,it told me that there is no "SCM_model",how to solve this problem?Looking forward to your reply

**Comment by akjayant** [comment]
I haven't uploaded model file yet. First run the 
'python safety_train False'    to collect data and then 'python safety_train True' to train safety model which will give SCM_model.

**Comment by forlornLT** [comment]
sorry to bother again,if there is a module named"torchsampler"?I can't find and install it

**Comment by akjayant** [comment]
Okay I will get back to you on this, maybe I have to upload the module because I modified it a bit. Thanks for bringing this into notice.

**Comment by forlornLT** [comment]
> Okay I will get back to you on this, maybe I have to upload the module because I modified it a bit. Thanks for bringing this into notice.

Thanks a lot

**Comment by akjayant** [comment]
Done.

**Comment by forlornLT** [comment]
THANKS!!!!!!!Sorry to ask you again for the details: in the version 1 and 2,if i want to go on training ,i just need to load the saved policy_qnet and run "train.py" again; but in ver3 I dont know well about the effect of "safety_model False/True",like what you said,it provides the SCM_model,so I want to ask 3 questions:①what doe the "SCM_model" do?②if I want to go on training,should I run safety_model.py False 1time and True 1time, and then train.py many many times? is SCM_model trained well for those two py files ran each 1 time?③Did you meet a problem that "the sensor object went out of the scope but the sensor is still alive in the simulation:Actor xxxx" ?I think it is the problem in teacher cjy1992's gym-carla's function:reset() maybe is the destroy() in it ,how do you solve it?          my English is not well(sorry) and THANKS A LOT AGAIN TO YOU SINCERELY !!!!!

**Comment by akjayant** [comment]
1) So python safety_train.py False collects data as  <image,action,safety label (0,1)> tuple i.e, if I am in certain state and take action whether it will be safe or not. Safety is defined as whether it leads to lane invasion or collision.
2)  python safety_train.py True trains a supervised model SCM_model which takes in a frame an tells whether it is safe or not using the collected data.  It will be an unbalanced dataset so I kind of used balanced mini-batching (not perfect way but okayish). You have to run it just one time, you will have SCM_model.
2)  Now python train.py will train an RL algorithm that will use this SCM_model as a guide to check whether a frame is safe or not just like a guide sitting in a co-driver seat while you are learning to drive, an expert with prior knowledge.It will reset the agent if action is unsafe at that state, as our SCM_model will predict it.
3)  Not sure about gym-carla question., I thnk it has to destroy actors for resetting otherwise memory will overflow.
Also this is a very naive way to approach safety in RL, its just a okayish beginner project, did it just for fun :p
Happy to help. :) Happy learning.

**Comment by forlornLT** [comment]
Thank you so much. I've learned so much from you

> 1. So python safety_train.py False collects data as  <image,action,safety label (0,1)> tuple i.e, if I am in certain state and take action whether it will be safe or not. Safety is defined as whether it leads to lane invasion or collision.
> 2. python safety_train.py True trains a supervised model SCM_model which takes in a frame an tells whether it is safe or not using the collected data.  It will be an unbalanced dataset so I kind of used balanced mini-batching (not perfect way but okayish). You have to run it just one time, you will have SCM_model.
> 3. Now python train.py will train an RL algorithm that will use this SCM_model as a guide to check whether a frame is safe or not just like a guide sitting in a co-driver seat while you are learning to drive, an expert with prior knowledge.It will reset the agent if action is unsafe at that state, as our SCM_model will predict it.
> 4. Not sure about gym-carla question., I thnk it has to destroy actors for resetting otherwise memory will overflow.
>    Also this is a very naive way to approach safety in RL, its just a okayish beginner project, did it just for fun :p
>    Happy to help. :) Happy learning.
